workflows:
  ios-build:
    name: Build iOS app
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build the Ionic app
        script: |
          ionic build
      - name: Sync Capacitor
        script: |
          ionic capacitor copy ios
      - name: List available schemes
        script: |
          cd ios/App
          xcodebuild -list
      - name: Run iOS build
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive archive
    artifacts:
      - build/**/*.ipa